# Generated by Django 6.0.7 on 2026-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('Work', models.CharField(max_length=100)),
            ],
        ),
    ]
