# Generated by Django 6.0.7 on 2026-07-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_recent_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='journal/')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
